version: '3'
services:
  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations/products.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/users?sslmode=disable
    ports:
      - '8080:8080'
    depends_on:
      - postgres